name: parsepglog
version:             0.1.0.0
license:             BSD3
author:              "Harry Maclean"
maintainer:          "harryjmaclean@gmail.com"
copyright:           "2018 Harry Maclean"
description:         Parse PG logs

dependencies:
- base >= 4.7 && < 5
- text
- time
- megaparsec
- attoparsec

library:
  source-dirs: src

executables:
  parsepglog:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - parsepglog
    - text
    - time
    - pretty-simple
    - bytestring
    - zlib
